# Generated by Django 3.0.8 on 2020-08-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlalgorithm',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
